### ISSUE TITLE
Unable to look up a name or access an attribute

### ISSUE THREAD

**Issue by dewolfs** [konstantin-kelemen/ansible-role-percona-cluster#1]
Hi,

Executing this role, gives me the following error with verbose output.

TASK [konstantin-kelemen.percona-cluster : Generate /etc/my.cnf] *************************************************************************************************************************************
task path: /etc/ansible/roles/konstantin-kelemen.percona-cluster/tasks/main.yml:16
fatal: [db801]: FAILED! => {
    "changed": false, 
    "msg": "AnsibleUndefinedVariable: Unable to look up a name or access an attribute in template string ([mysqld]\n\ndatadir = /var/lib/mysql\nuser = mysql\n\n# Path to Galera library\nwsrep_provider = /usr/lib64/libgalera_smm.so\n\n# Cluster connection URL contains the IPs of cluster nodes\n{# list of cluster members #}\n{% set cluster_members = [] -%}\n{%- for node in groups['percona'] %}\n  {%- set _ = cluster_members.append(hostvars[node].ansible_ssh_host) -%}\n{% endfor -%}\nwsrep_cluster_address = gcomm://{{ \",\".join(cluster_members) }}\n\n# In order for Galera to work correctly binlog format should be ROW\nbinlog_format = ROW\n\n# MyISAM storage engine has only experimental support\ndefault_storage_engine = InnoDB\n\n# This changes how InnoDB autoincrement locks are managed and is a requirement for Galera\ninnodb_autoinc_lock_mode = 2\n\n# Node address\nwsrep_node_address = {{ ansible_ssh_host }}\n\n# SST method\nwsrep_sst_method = xtrabackup-v2\n\n# Cluster name\nwsrep_cluster_name = {{ percona_cluster_name }}\n\n# Authentication for SST method\nwsrep_sst_auth = \"{{ percona_cluster_stt_user }}:{{ percona_cluster_stt_password }}\"\n).\nMake sure your variable name does not contain invalid characters like '-': sequence item 0: expected string, StrictUndefined found"
}

Kr,

Sam

**Comment by konstantin-kelemen** [comment]
Hi, thank you for taking your time for submitting this issue.

May I ask you to provide your inventory file?

By default you have to have the `percona` group with three members in it.

**Comment by konstantin-kelemen** [comment]
Mine looks the following way:

```
[percona]
percona-node01.test.com ansible_ssh_host=11.22.33.1
percona-node02.test.com ansible_ssh_host=11.22.33.2
percona-node03.test.com ansible_ssh_host=11.22.33.3
```
